### ISSUE TITLE
[issue] - table not showing the values

### ISSUE THREAD

**Issue by redmuchroom** [waccit/unified-red#37]
Hi Guys,

I'm trying to create a table with a list of data. However the values are not shown (the description well) and if I put a text with a part of the payload in the same tab it works well.

the payload looks like:
![image](https://user-images.githubusercontent.com/50101611/148079375-3e562f7c-eb5b-4d98-bc3d-98afd3877727.png)

and here is what i'm setting in the table:
![image](https://user-images.githubusercontent.com/50101611/148079532-8d186b91-7f0b-4cb7-b4bf-cd42bd928a0c.png)

I guess that I'm doing a stupid mistake somewhere but I've tried several things always with the same result (such as {{msg.payload.volt}} for example and nothing as filter)

context:
* Operating System: windows 10 
* Node.js version: 12.16.1
* npm version: 6.13.4
* Node-RED version: 2.1.4
* Unified-RED version: 2.0.15

thanks!!

**Comment by wac-dirka** [comment]
redmuchroom,

The table node appears to not be configured properly. The device filter field must have a value. And you’re correct that the text format field should be assigned something like {{msg.payload.volt}} since the values you’re mapping are properties of the payload object.

To configure the device filter and parameter filter...copied from the table help section:

> **Device Filter** : Used to generate rows (or columns when pivoted) based on the messages received. Setting to SmartServer IoT will detect devices using the SmartServer IoT IAP topic schema. Custom allows you to provide a regular expression that will be applied to incoming messages. When providing a custom regular expression, two capture groups should be provided. Group 1 should be a unique segment of the message topic that represents the device name or instance. Similarly, group 2 should indicate the data point segment within the topic. Group 2 is used by Parameter Filter.
> **Parameter Filter** : The data point name (or a portion of it) used to map the data point to a cell.

Assuming you’re topic schema is something like “site/device/point”, a custom device filter regular expression could be:
([^\/]+\/[^\/]+)\/(.*)
Where group 1 consists of one or more non-slash characters (site name), followed by a slash, followed by one or more non-slash characters (device name). And group 2 consists of any number of characters (data point name). Depending on your actual topic schema you’ll need to adjust this accordingly.

I hope this helps.

**Comment by redmuchroom** [comment]
working like a charm! :) 
thanks for the help!
